version: "3.7"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:0.20.2099
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true
    dns:
      - ${DNS_IP}
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media/torrents:/media/torrents
    ports:
      - ${APP_PORT}:9117
    restart: unless-stopped
    networks:
      - tipi_main_network
