version: "3.7"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.19
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/data/books:/books
    ports:
      - ${APP_PORT}:8083
    restart: unless-stopped
    networks:
      - tipi_main_network
