version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:0.47.5
    ports:
      - ${APP_PORT}:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - ${APP_DATA_DIR}/navidrome/data:/data
      - ${ROOT_FOLDER_HOST}/media/data/music:/music:ro 
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.navidrome.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.routers.navidrome.service: navidrome
      traefik.http.routers.navidrome.tls.certresolver: myresolver
      traefik.http.services.navidrome.loadbalancer.server.port: 4533
