version: "3.7"
services:
  monerod:
    image: sethsimmons/simple-monerod:v0.18.1.1
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:18080
    restart: unless-stopped
    networks:
      - tipi_main_network
    container_name: monerod
    volumes:
      - ${APP_DATA_DIR}/data:/home/monero/.bitmonero
    command: >-
      --rpc-restricted-bind-ip=0.0.0.0
      --rpc-restricted-bind-port=18089
      --public-node
      --no-igd
      --enable-dns-blocklist
      --prune-blockchain
      --zmq-pub=tcp://0.0.0.0:18083
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.monerod.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.monerod.entrypoints: websecure
      traefik.http.routers.monerod.service: monerod
      traefik.http.routers.monerod.tls.certresolver: myresolver
      traefik.http.services.monerod.loadbalancer.server.port: 18089
