version: "3.9"
services:
  kavita:
    image: kizaing/kavita:0.5.6
    container_name: kavita
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/manga:/manga
      - ${ROOT_FOLDER_HOST}/media/data/comics:/comics
      - ${ROOT_FOLDER_HOST}/media/data/books:/books
      - ${APP_DATA_DIR}/data/config:/kavita/config
    ports:
      - ${APP_PORT}:5000
    restart: unless-stopped
    networks:
      - tipi_main_network
      